### ISSUE TITLE
Documentation links to wrong name on PyPI

### ISSUE THREAD

**Issue by afontenot** [vstinner/pyperf#50]
https://pypi.org/project/pyperf/#history shows that a different project replaced this one in Dec 2018 of last year. The documentation for pyperf still points to this link and the pip installation instructions install the other project. (I found this out after installing it by accident.)

Has this project been abandoned? Deleted from PyPI? Is this a security issue?

**Comment by afontenot** [comment]
Never mind. I see you very recently changed the name of the project to "pyperf"; however the project is still on PyPI at https://pypi.org/project/perf/.

This was very confusing, since even the README was changed to point to pyperf. Leaving this open until the documentation can be fixed.

**Comment by vstinner** [comment]
I just renamed my "perf" project to "pyperf" to avoid confusion with the Linux perf program which has a Python binding using "perf" name as well: commit https://github.com/vstinner/pyperf/commit/60eb936a87e287c578e85ab33b8b9a91d609ba53

I checked that pyperf.readthedocs.io was available, but I only noticed that http://pypi.org/project/pyperf/ is already used *after* I pushed my change :-(

I contacted http://pypi.org/project/pyperf/ author ( http://brucespang.com/ ) to see if he would be to give me this name on PyPI.

If I don't get any answer from him, it seems like I will have to pick a different name. The safe option is simply to revert my big rename commit, and rename again the GitHub project (if possible!).

**Comment by afontenot** [comment]
Personally I don't think there would be too much confusion from keeping the name perf. Distributions are shipping it as "python-perf", and it's already a well-known name attested elsewhere, for instance in this output when using timeit:

    % pypy3 -mtimeit      
    WARNING: timeit is a very unreliable tool. use perf or something else for real measurements
    pypy3 -m pip install perf
    pypy3 -m perf timeit 
    ------------------------------------------------------------

**Comment by daurnimator** [comment]
> I just renamed my "perf" project to "pyperf" to avoid confusion with the Linux perf program which has a Python binding using "perf" name as well

Thankyou!

This has been causing conflicts on my system :)
Was about to file an issue but it was already fixed: please don't revert!

**Comment by vstinner** [comment]
> Thankyou!
> This has been causing conflicts on my system :)
> Was about to file an issue but it was already fixed: please don't revert!

It's not done yet, I don't know http://pypi.org/project/pyperf/ yet

**Comment by paugier** [comment]
I agree that it would be much better to find another name than "perf", which is already taken by 
https://perf.wiki.kernel.org

pyperf would be perfect. 

https://github.com/brucespang/pyperf does not seem to be a big project (only 2 commits). 

@brucespang would you mind to "give" http://pypi.org/project/pyperf/ to @vstinner ? It would be the simplest solution.

**Comment by vstinner** [comment]
The project is now officially renamed to pyperf (since its version 1.6.1). I even removed http://pypi.org/project/perf to force users to change their habbits, but the name was taken again in less than 2 hours! http://pypi.org/project/perf is now a different project.
