### ISSUE TITLE
Tests fail on Python 2: AttributeError: .. object has no attribute 'assertRegex'

### ISSUE THREAD

**Issue by jayvdb** [vstinner/pyperf#57]
The setup.py & tests dont declare unittest2 as a mandatory dependency on Python 2, but tox includes it.

Just running setup.py test or nose without it:

```py
[   84s] _____________________________ TestTimeit.test_name _____________________________
[   84s] 
[   84s] self = <pyperf.tests.test_timeit.TestTimeit testMethod=test_name>
[   84s] 
[   84s]     def test_name(self):
[   84s]         name = 'myname'
[   84s]         args = PERF_TIMEIT + ('--name', name) + FAST_BENCH_ARGS
[   84s]         bench, stdout = self.run_timeit_bench(args)
[   84s]     
[   84s]         self.assertEqual(bench.get_name(), name)
[   84s] >       self.assertRegex(stdout, re.compile('^%s' % name, flags=re.MULTILINE))
[   84s] E       AttributeError: 'TestTimeit' object has no attribute 'assertRegex'
[   84s] 
[   84s] pyperf/tests/test_timeit.py:254: AttributeError
[   84s] ============== 17 failed, 143 passed, 1 skipped in 13.43 seconds ===============
```

Note using six doesnt help; I run into https://github.com/benjaminp/six/issues/164

**Comment by vstinner** [comment]
pyperf requires unittest2 on Python 2.

"tox -e py27" is the recommended way to run tests. unittest2 is a test dependency in tox.ini.

> The setup.py & tests dont declare unittest2 as a mandatory dependency on Python 2, but tox includes it.

In Python, it's complex to declare dependencies only depending on the Python version and only for tests.

**Comment by jayvdb** [comment]
What about adding an exception in the tests if unittest2 wasnt found on Python 2?

**Comment by vstinner** [comment]
> What about adding an exception in the tests if unittest2 wasnt found on Python 2?

You can do that in pyperf/tests/__init__.py. If you write such code and it would only change the behavior on Python 2, I would accept such pull request ;-)

**Comment by vstinner** [comment]
On Python 2, pyperf has 3 additional test dependencies (compared to Python 3): contextlib2, mock, unittest2. The code should fail with an ImportError if mock or contextlib2 is missing on Python 2.

**Comment by jayvdb** [comment]
Or I can add a backport of assertRegex, if that is the only bit missing (e.g. https://github.com/kyrias/python-srcinfo/pull/10)
Anyways, will PR soon.
